appender.console.type=Console
appender.console.name=Console
appender.console.target=SYSTEM_OUT
appender.console.immediateFlush=true
appender.console.layout.type=PatternLayout
appender.console.layout.pattern=%d{yyyy-MM-dd'T'HH:mm:ss.SSS'Z'}{UTC} [%t] %-5level %logger{36} - %msg%n

rootLogger.level=INFO
rootLogger.appenderRefs=stdout
rootLogger.appenderRef.stdout.ref=Console
